// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $blog from "./routes/blog.tsx";
import * as $dashboard_activity_feed from "./routes/dashboard/activity-feed.tsx";
import * as $heatmap from "./routes/heatmap.tsx";
import * as $index from "./routes/index.tsx";
import * as $profile_layout from "./routes/profile/_layout.tsx";
import * as $profile_activities from "./routes/profile/activities.tsx";
import * as $profile_challenges from "./routes/profile/challenges.tsx";
import * as $profile_followers from "./routes/profile/followers.tsx";
import * as $profile_gear from "./routes/profile/gear.tsx";
import * as $profile_index from "./routes/profile/index.tsx";
import * as $profile_routes from "./routes/profile/routes.tsx";
import * as $profile_segments from "./routes/profile/segments.tsx";
import * as $profile_user from "./routes/profile/user.tsx";
import * as $routes_slug_ from "./routes/routes/[slug].tsx";
import * as $training_activities_slug_ from "./routes/training/activities/[slug].tsx";
import * as $training_my_activities from "./routes/training/my-activities.tsx";
import * as $upload from "./routes/upload.tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/blog.tsx": $blog,
    "./routes/dashboard/activity-feed.tsx": $dashboard_activity_feed,
    "./routes/heatmap.tsx": $heatmap,
    "./routes/index.tsx": $index,
    "./routes/profile/_layout.tsx": $profile_layout,
    "./routes/profile/activities.tsx": $profile_activities,
    "./routes/profile/challenges.tsx": $profile_challenges,
    "./routes/profile/followers.tsx": $profile_followers,
    "./routes/profile/gear.tsx": $profile_gear,
    "./routes/profile/index.tsx": $profile_index,
    "./routes/profile/routes.tsx": $profile_routes,
    "./routes/profile/segments.tsx": $profile_segments,
    "./routes/profile/user.tsx": $profile_user,
    "./routes/routes/[slug].tsx": $routes_slug_,
    "./routes/training/activities/[slug].tsx": $training_activities_slug_,
    "./routes/training/my-activities.tsx": $training_my_activities,
    "./routes/upload.tsx": $upload,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
